In [501]:
from sklearn.ensemble import AdaBoostClassifier

In [502]:
dict={}

In [503]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [504]:
i = pd.read_csv('odd.csv') 

In [505]:
i.head(5)

Species  Weight  Length2  Length3   Height   Width
0   Bream   242.0     25.4     30.0  11.5200  4.0200
1   Bream   290.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     26.5     31.1  12.3778  4.6961
3   Bream   363.0     29.0     33.5  12.7300  4.4555
4   Bream   430.0     29.0     34.0  12.4440  5.1340

In [506]:
X = i.iloc[:,2:6].values
y = i.iloc[:,:1].values

In [507]:
from sklearn.model_selection import train_test_split
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

#first model using svc(support vector machine)

In [508]:

from sklearn.svm import SVC
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
svc=SVC(probability=True, kernel='linear')

# Create adaboost classifer object
abc =AdaBoostClassifier(n_estimators=50, base_estimator=svc,learning_rate=1)

# Train Adaboost Classifer
model = abc.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = model.predict(X_test)


# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
z1=metrics.accuracy_score(y_test, y_pred)


Accuracy: 0.5681818181818182


In [509]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[ 6,  0,  0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0],
       [ 0,  0, 19,  0,  0,  0],
       [ 0,  0,  5,  0,  0,  0],
       [ 0,  0,  9,  0,  0,  0],
       [ 0,  0,  2,  0,  0,  0]], dtype=int64)

#second model using decision treee classifier

In [510]:
from sklearn.tree import DecisionTreeClassifier
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
dt1 = DecisionTreeClassifier( max_depth=1)

# Create adaboost classifer object
abc =AdaBoostClassifier(n_estimators=50, base_estimator=dt1,learning_rate=1)

# Train Adaboost Classifer
model = abc.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = model.predict(X_test)


# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
z2=metrics.accuracy_score(y_test, y_pred)


Accuracy: 0.5


#using naive bayle

In [511]:
from sklearn.naive_bayes import GaussianNB
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
dt2 = GaussianNB()

# Create adaboost classifer object
abc =AdaBoostClassifier(n_estimators=50, base_estimator=dt2,learning_rate=1)

# Train Adaboost Classifer
model = abc.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = model.predict(X_test)


# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
z3=metrics.accuracy_score(y_test, y_pred)

Accuracy: 0.6136363636363636


In [512]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[ 6,  0,  0,  0,  0,  0],
       [ 0,  3,  0,  0,  0,  0],
       [ 0,  0, 16,  0,  3,  0],
       [ 0,  0,  4,  1,  0,  0],
       [ 0,  1,  7,  0,  1,  0],
       [ 0,  0,  2,  0,  0,  0]], dtype=int64)

#using logistic regression

In [513]:
from sklearn.linear_model import LogisticRegression
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
dt3 = LogisticRegression()

# Create adaboost classifer object
abc =AdaBoostClassifier(n_estimators=50, base_estimator=dt3,learning_rate=1)

# Train Adaboost Classifer
model = abc.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = model.predict(X_test)


# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


Accuracy: 0.7272727272727273


In [514]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

array([[6, 0, 0, 0, 0, 0],
       [0, 3, 0, 0, 0, 0],
       [0, 0, 9, 0, 8, 2],
       [0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 7, 2],
       [0, 0, 0, 0, 0, 2]], dtype=int64)

In [515]:
z=metrics.accuracy_score(y_test, y_pred)

In [516]:
l = []
 
# create a dictionary with student details
final = {1:z1,
    2:z2,
    3: z3,
    4:z
           }
 
# append this dictionary to
# the empty list using deepcopy() method
l.append(final)
 

In [517]:
max(l)

{1: 0.5681818181818182, 2: 0.5, 3: 0.6136363636363636, 4: 0.7272727272727273}

In [518]:
import operator
MaxKey = max(final.items(), key = operator.itemgetter(1))[0]
print("The model with maximum  accuracy  is :\n",MaxKey)
d=MaxKey


The model with maximum  accuracy  is :
 4


In [519]:

models = {1:"support vector machine",
    2:"decision tree classifer",
    3: "naive bayles",
    4:"logistic"
           }
# convert the dictionary to list using items()
dictlist = list(models.items())
# using indexing we can print the first key value pair of dictionary
print( dictlist[d-1])

(4, 'logistic')
